name: Rust and Cypress Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build --verbose

  e2e-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run
      run: cargo run

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: clone cypress-example-todomvc
      run: git clone https://github.com/cypress-io/cypress-example-todomvc.git cypress-example-todomvc

    - name: install dependencies
      run: |
        cd cypress-example-todomvc
        npm install

    - name: run e2e Cypress test
      run: |
        cd cypress-example-todomvc
        npm run cypress:run

    - name: stop cargo run
      run: pkill -f "cargo run"
